### ISSUE TITLE
template parameter redefines default argument error when compiling with Clang.

### ISSUE THREAD

**Issue by phuongtran7** [Svalorzen/asn1cpp#3]
Hi,

When I tried compiling the test project with Clang 10, both on Windows and in WSL Ubuntu 20.04, I got the error `template parameter redefines default argument`:

```
D:\Projects\TestASN1\TestASN1\external\asn1cpp\Encoding.hpp(29,42): error : template parameter redefines default argument
          template <typename T, typename = typename std::enable_if<is_asn1_wrapper<T>::value>::type>
                                           ^
D:\Projects\TestASN1\TestASN1\external\asn1cpp\Seq.hpp(18,42): note: previous default template argument defined here
          template <typename T, typename = typename std::enable_if<is_asn1_wrapper<T>::value>::type>
                                           ^
```

However, the same code compiled just fine with MSVC 19.26 on Windows and GCC 9.3 on Ubuntu. Is this the intended behavior? I just want to ask so that I can make a note in my readme later.

Thank you so much for your time and help.

**Comment by Svalorzen** [comment]
Hey, it was a problem with a forward declaration. Can you try again with current master?

**Comment by phuongtran7** [comment]
Hi,

Thank you again for your extremely fast response. I was able to test with Clang 10 on both Windows and WSL Ubuntu, both worked great. No more error. And both MSVC and GCC still works fine too.

With this I don't have to worry about this in the readme anymore. Thank you so much for your time and help. I really appreciate it.

Do you want me to close the issue?

**Comment by Svalorzen** [comment]
Yeah, feel free to close it :)
